---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  my-statefulset-third
  namespace: kman
  labels:
    app: kcluster
spec:
  serviceName: my-headless-service
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: kcluster
  template:
    metadata:
      labels:
        app: kcluster
    spec:
      containers:
      - name: kafkamantwo
        image: bumory1987/kafkaman:0.002
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: NODE_ID
          value: "3"
        - name: CONNECTOR
          value: "1@my-statefulset-0.my-headless-service.kman.svc.cluster.local:9093,2@my-statefulset-sec-0.my-headless-service.kman.svc.cluster.local:9093,3@my-statefulset-third-0.my-headless-service.kman.svc.cluster.local:9093"
        - name: IP_NAME
          value: "my-statefulset-third-0.my-headless-service.kman.svc.cluster.local"
