---
apiVersion: v1
kind: Service
metadata:
  name: flink-loadbalancer
  namespace: flinkman
spec:
  selector:
    pos: master
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer