---
apiVersion: v1
kind: Namespace
metadata:
  name: kman
---
apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
  namespace: kman
spec:
  clusterIP: None
  selector:
    app: kcluster
  ports:
  - name: port-9093
    port: 9093
    targetPort: 9093
  - name: port-9092
    port: 9092
    targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-loadbalancer
  namespace: kman
spec:
  selector:
    app: kcluster
  ports:
    - protocol: TCP
      port: 9024
      targetPort: 9024
  type: LoadBalancer
