---
apiVersion: v1
kind: Service
metadata:
  name: kafka-loadbalancer
  namespace: kman
spec:
  selector:
    app: kcluster
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
  type: LoadBalancer