apiVersion: v1
kind: Service
metadata:
  name: springman-ssh
  namespace: kman
spec:
  type: NodePort
  selector:
    app: kcluster
    ssh: spring
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30222
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080