---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: springman
  namespace: kman
  labels:
    app: kcluster
spec:
  serviceName: "my-headless-service"
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: kcluster
      ssh: spring
  template:
    metadata:
      labels:
        app: kcluster
        ssh: spring
    spec:
      hostNetwork: true
      containers:
      - name: kafkaman
        image: bumory1987/basic:0.02
        ports:
        - containerPort: 22
        - containerPort: 8082
    