---
apiVersion: v1
kind: Namespace
metadata:
  name: kman
---
apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
  namespace: kman
spec:
  clusterIP: None
  selector:
    app: kcluster
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-loadbalancer
  namespace: kman
spec:
  selector:
    app: kcluster
  ports:
    - protocol: TCP
      port: 9024
      targetPort: 9024
  type: LoadBalancer
